# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLIENTE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(max_length=15, verbose_name='Tel\xe9fono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo-e')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='IMAGEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='tininiska/imgs')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripci\xf3n')),
                ('titulo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.CreateModel(
            name='PAQUETE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripci\xf3n')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Costo U$')),
            ],
            options={
                'verbose_name': 'Paquete',
                'verbose_name_plural': 'Paquetes',
            },
        ),
        migrations.CreateModel(
            name='RESERVACION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_res', models.DateField(verbose_name='Fecha de Reservaci\xf3n')),
                ('cant_pers', models.PositiveIntegerField(verbose_name='Cantidad de Personas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tininiska.CLIENTE')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tininiska.PAQUETE')),
            ],
            options={
                'ordering': ['fecha_res'],
                'verbose_name': 'Reservaci\xf3n',
                'verbose_name_plural': 'Reservaciones',
            },
        ),
        migrations.AddField(
            model_name='imagen',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='tininiska.PAQUETE'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='paquetes_res',
            field=models.ManyToManyField(through='tininiska.RESERVACION', to='tininiska.PAQUETE'),
        ),
    ]
