# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-25 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tininiska', '0002_auto_20170725_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='paquetes',
            new_name='paquete',
        ),
    ]
