# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-25 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tininiska', '0003_auto_20170725_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='paquete',
        ),
    ]
