# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-26 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tininiska', '0004_remove_cliente_paquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='paquetes_res',
            field=models.ManyToManyField(through='tininiska.RESERVACION', to='tininiska.PAQUETE'),
        ),
    ]
