# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-26 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tininiska', '0006_auto_20170726_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='paquetes_resvados',
            new_name='paquetes_res',
        ),
    ]
